### ISSUE TITLE
Spotify++ (w/ Sposify)

### ISSUE THREAD

**Issue by yodaluca23** [qnblackcat/My-AltStore-repo#10]
I've noticed that you've been keeping Spotify++ (w/ Sposify) up to date on AppDB [here](https://appdb.to/app/cydia/1900000540). Any chance you could add that .ipa to this repo? As well keep it up to date here?

**Comment by yodaluca23** [comment]
Also speaking of Spotify++ (w/ Sposify) Could you do what you do with uYou+ to this, where you remove all the unnecessary ID's?

**Comment by qnblackcat** [comment]
I’m no longer providing tweaked Spotify ipa
