### ISSUE TITLE
different `bundleIdentifier`s for cercube and uYou+

### ISSUE THREAD

**Issue by DetachHead** [qnblackcat/My-AltStore-repo#3]
altstore seems to get confused by the fact that there are two apps with the same `bundleIdentifier`, maybe they can be changed to something like `io.github.qnblackcat.cercube` and `io.github.qnblackcat.uyouplus`

for example, i clicked download on uYou+, clicked the browse tab and then it showed the downloading progress bar on cercube instead

**Comment by qnblackcat** [comment]
True. It seems like we need to use a unique `bundleidentifier` for each app.

Let's hope that changing the bundle ID won’t mess up the ability to install apps directly through AltStore.

**Comment by DetachHead** [comment]
Looks like it does unfortunately 

![8224272A-F264-4773-9AD5-B80E37804EB2](https://user-images.githubusercontent.com/57028336/146619325-bac85a7c-3614-43b9-a1d8-2bbe9ceab184.jpeg)

**Comment by qnblackcat** [comment]
Modifying YouTube's bundle ID is not a good idea since it can break Google Sign-in. Seems like removing Cercube+ is the only option.
