### ISSUE TITLE
Source no longer works on altstore

### ISSUE THREAD

**Issue by jeffzyliu** [qnblackcat/My-AltStore-repo#5]
As of this commit: https://github.com/qnblackcat/AltStore/commit/fc7e5379ae45fc805f20649712637551de0694d7

the apps.json source doesn't work anymore. This error occurs:
![image](https://user-images.githubusercontent.com/28827171/162659714-038915f1-a188-4387-909c-8c02e462ef0a.png)

The apps.json from the commit right before works just fine though.

**Comment by qnblackcat** [comment]
thank for your report! It should work now.

**Comment by jeffzyliu** [comment]
Thanks for the fix!
