### ISSUE TITLE
Please keep up to date.

### ISSUE THREAD

**Issue by yodaluca23** [qnblackcat/My-AltStore-repo#9]
I would like to use this to keep my uYou+ up to date, but the latest release on this repo is "v17.43.1 (2.1)" while the latest uYou+ is "17.48.2 (2.1)"... it would be super convenient for me to be able to use this to keep my uYou+ automatically updated...

**Comment by qnblackcat** [comment]
Ok

**Comment by yodaluca23** [comment]
@qnblackcat It's behind again with the [latest uYou+ update](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.49.6-2.1)...

Edit: Completed, thank u.

**Comment by WoodpeckerBaby** [comment]
Still behind

**Comment by yodaluca23** [comment]
Yea, @qnblackcat it's behind again, please update it...
